version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env
#    environment:
#      - NODE_ENV=development
#      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-app_dev}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER:-postgres}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
#      - POSTGRES_DB=${POSTGRES_DB:-app_dev}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_dev_data:
    driver: local
