version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
#    environment:
#      - NODE_ENV=production
#      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-app}
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER:-postgres}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
#      - POSTGRES_DB=${POSTGRES_DB:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
