name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Package application
      run: |
        mkdir -p deploy
        cp target/*.jar deploy/
        cp -r scripts deploy/
        cp -r target/lib deploy/lib
        chmod +x deploy/scripts/*.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: yassinebot-build
        path: deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: yassinebot-build
        path: deploy

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        scp -r deploy/* $SSH_USER@$SSH_HOST:$DEPLOY_PATH/
        ssh $SSH_USER@$SSH_HOST "cd $DEPLOY_PATH && ./scripts/restart.sh"

    - name: Log deployment completion
      run: echo "Deployment completed successfully"
