name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV }}" > .env
          echo ".env file created successfully"
          # Affiche les variables sans leurs valeurs pour vérification (sécurisé)
          grep -o '^[^=]*=' .env | sort

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Create PM2 ecosystem file
        run: |
          cat > ecosystem.config.cjs << EOF
          module.exports = {
            apps: [{
              name: "bot",
              script: "yarn",
              args: "run start",
              watch: false,
              autorestart: true,
              max_restarts: 10,
              min_uptime: "5s",
              max_memory_restart: "1G",
              error_file: "logs/err.log",
              out_file: "logs/out.log",
              merge_logs: true,
              time: true,
              env: {
                NODE_ENV: "production"
              }
            }]
          }
          EOF

      - name: Configure and Start PM2 service
        run: |
          if pm2 list | grep -q "bot"; then
            pm2 delete bot
          fi
          pm2 start ecosystem.config.cjs
          pm2 startup
          pm2 save

      - name: Check PM2 status and logs
        run: |
          pm2 status
          echo "Errors :"
          tail -n 5 logs/err.log || true
          echo "Output :"
          tail -n 5 logs/out.log || true

